LittlerootTown_Gym_MapScripts::
	.byte 0


LittlerootTown_Gym_EventScript_GymStatue::
	lockall
	msgbox LittlerootTown_Gym_EventScript_GymStatue_Text_0
	releaseall
	end


LittlerootTown_Gym_EventScript_Guide::
	lockall
	msgbox LittlerootTown_Gym_EventScript_Guide_Text_0
	releaseall
	end


LittlerootTown_Gym_EventScript_GymStatue_Text_0:
	.string "LITTLEROOT TOWN GYM$"

LittlerootTown_Gym_EventScript_Guide_Text_0:
	.string "insert speech here$"
